name: react_test

on: 
  push:
    branches:
      - "master"

jobs:
  test_run:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Set-up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: setting dependency cache
        id: node_cache
        uses: actions/cache@v3
        with:
          # we ca use the cache the node modules folder in place of the npm directory to make the execution faster path: ~/.npm 
          path: node_modules
          key: dep-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: ${{ steps.node_cache.output.cache_hit }} != 'true'
        run: npm ci
      - name: Run test
        run: npm run test
  build:   
    needs: [test_run]
    runs-on: ubuntu-latest
    outputs:
      script-files: ${{steps.publish.outputs.script-file}}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Set-up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: checkout for cache
        id: cache_setup
        uses: actions/cache@v3
        with:
          path: node_modules
          key: dep-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.cache_setup.outputs.cache-hit != 'true'
        run: npm ci
      - name: deploy build
        run: npm run build
        ## using the outputs from the job which can be used in other jobs is done as below
      - name: js-file-output
        id: publish
        run: find dist/assets/*js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
        ## as the job is completed the data is lost as the runnier is shut down to save the same we need to use the artifacts
      - name: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deployment: 
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: deployment
        run: echo "now running deployment"
      - name: download-artifacts
        id: download_artifacts
        uses: actions/download-artifact@v3
        with: 
          name: dist-files
      - name: Getting output from build
      ## There are many other function which are helpful to overwrite the default behaviour of the actions like the failure(), success() cancelled() and always()
        if: steps.download_artifacts.outcome == 'success'
        run: |
          echo "Printing the output"
          echo "${{ needs.build.outputs.script-files }}"
      - name: see contents
        run: ls